# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='citations',
            field=models.TextField(blank=True, verbose_name='Citations/References'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='citations_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1, verbose_name='Render citations as'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='citations',
            field=models.TextField(blank=True, verbose_name='Citations/References'),
        ),
        migrations.AddField(
            model_name='exhibititem',
            name='citations_render_as',
            field=models.CharField(choices=[('H', 'HTML'), ('T', 'Plain Text'), ('M', 'Markdown')], default='H', max_length=1, verbose_name='Render citations as'),
        ),
    ]
